language: csharp
solution: Fletcher.sln
install:
  - nuget restore Fletcher.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Fletcher.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Fletcher.UnitTests/bin/Release/Fletcher.UnitTests.dll ./src/Fletcher.IntegrationTests/bin/Release/Fletcher.IntegrationTests.dll
